/**
 * Utility functions for working with demo steps
 */

export interface BubbleConfig {
  text: string;
  position?: 'auto' | 'top' | 'bottom' | 'left' | 'right';
  style?: 'tooltip' | 'callout' | 'speech';
  autoGenerated?: boolean;
}

export interface StepData {
  id?: string;
  type?: string;
  step_type?: string;
  action_type?: string;
  event_type?: string;
  element?: any;
  element_data?: any;
  annotations?: {
    text?: string;
    bubble?: BubbleConfig;
    playback?: {
      zoom?: {
        enabled: boolean;
        scale: number;
        focusX: number;
        focusY: number;
        autoGenerated?: boolean;
      };
    };
  };
  screenshot_url?: string;
  value?: string;
  url?: string;
}

/**
 * Default zoom configuration
 */
export const DEFAULT_ZOOM = {
  scale: 1,
  focusX: 50,
  focusY: 50,
} as const;

export const AUTO_ZOOM_INTERACTION_TYPES = new Set([
  "click",
  "input",
  "change",
  "submit",
  "focus",
]);

const AUTO_ZOOM_TARGET_RATIO = 0.35; // Less aggressive target (was 0.45)
const AUTO_ZOOM_MAX_SCALE = 1.5; // Gentler max scale
const AUTO_ZOOM_MIN_SCALE_DIFF = 0.05;
const AUTO_ZOOM_FOCUS_PADDING = 15; // More padding from edges (was 5)

function clamp(value: number, min: number, max: number) {
  return Math.min(Math.max(value, min), max);
}

function normalizeBoundingRect(rect: any) {
  if (!rect) {
    return null;
  }

  const width =
    typeof rect.width === "number"
      ? rect.width
      : typeof rect.right === "number" && typeof rect.left === "number"
        ? rect.right - rect.left
        : undefined;
  const height =
    typeof rect.height === "number"
      ? rect.height
      : typeof rect.bottom === "number" && typeof rect.top === "number"
        ? rect.bottom - rect.top
        : undefined;

  if (!width || !height) {
    return null;
  }

  const x =
    typeof rect.x === "number"
      ? rect.x
      : typeof rect.left === "number"
        ? rect.left
        : 0;
  const y =
    typeof rect.y === "number"
      ? rect.y
      : typeof rect.top === "number"
        ? rect.top
        : 0;

  return { x, y, width, height };
}

export interface AutoZoomResult {
  scale: number;
  focusX: number;
  focusY: number;
  shouldPersist: boolean;
}

export function calculateAutoZoom(step: StepData): AutoZoomResult {
  const elementData = getElementData(step);
  if (!elementData) {
    return { ...DEFAULT_ZOOM, shouldPersist: false };
  }

  const viewport = elementData.viewport;
  const boundingRect =
    normalizeBoundingRect(elementData.boundingRect) ||
    normalizeBoundingRect(elementData.bounding_rect);

  const stepType = getStepType(step)?.toLowerCase();

  if (
    !viewport ||
    typeof viewport.width !== "number" ||
    typeof viewport.height !== "number" ||
    viewport.width <= 0 ||
    viewport.height <= 0 ||
    !boundingRect ||
    boundingRect.width <= 0 ||
    boundingRect.height <= 0 ||
    stepType === "navigation" ||
    stepType === "scroll"
  ) {
    return { ...DEFAULT_ZOOM, shouldPersist: false };
  }

  const widthRatio = boundingRect.width / viewport.width;
  const heightRatio = boundingRect.height / viewport.height;

  let scale = 1;

  if (
    widthRatio < AUTO_ZOOM_TARGET_RATIO ||
    heightRatio < AUTO_ZOOM_TARGET_RATIO
  ) {
    const requiredWidthScale =
      widthRatio > 0 ? AUTO_ZOOM_TARGET_RATIO / widthRatio : AUTO_ZOOM_MAX_SCALE;
    const requiredHeightScale =
      heightRatio > 0
        ? AUTO_ZOOM_TARGET_RATIO / heightRatio
        : AUTO_ZOOM_MAX_SCALE;

    scale = Math.max(1, requiredWidthScale, requiredHeightScale);
    scale = clamp(Number(scale.toFixed(2)), 1, AUTO_ZOOM_MAX_SCALE);
  }

  const centerX = boundingRect.x + boundingRect.width / 2;
  const centerY = boundingRect.y + boundingRect.height / 2;

  // Calculate element center as percentage
  let focusX = (centerX / viewport.width) * 100;
  let focusY = (centerY / viewport.height) * 100;

  // Smart centering: pull toward 50% for comfortable viewing,
  // but respect edge constraints to prevent clipping
  const EDGE_THRESHOLD = 15; // Elements within 15% of edge stay at edge
  const CENTER_TARGET = 50;

  // Calculate how much of the element will be visible at each edge when zoomed
  const scaledElementWidth = (boundingRect.width * scale) / viewport.width * 100;
  const scaledElementHeight = (boundingRect.height * scale) / viewport.height * 100;

  // Minimum safe distance from edge (half the scaled element size)
  const minSafeX = scaledElementWidth / 2;
  const maxSafeX = 100 - scaledElementWidth / 2;
  const minSafeY = scaledElementHeight / 2;
  const maxSafeY = 100 - scaledElementHeight / 2;

  // If element is very close to an edge, keep it at the safe edge position
  if (focusX < EDGE_THRESHOLD) {
    focusX = Math.max(focusX, minSafeX);
  } else if (focusX > (100 - EDGE_THRESHOLD)) {
    focusX = Math.min(focusX, maxSafeX);
  } else {
    // Element is not near an edge, pull toward center for better composition
    focusX = clamp(focusX, minSafeX, maxSafeX);
  }

  if (focusY < EDGE_THRESHOLD) {
    focusY = Math.max(focusY, minSafeY);
  } else if (focusY > (100 - EDGE_THRESHOLD)) {
    focusY = Math.min(focusY, maxSafeY);
  } else {
    // Element is not near an edge, pull toward center for better composition
    focusY = clamp(focusY, minSafeY, maxSafeY);
  }

  const shouldPersist =
    scale - 1 > AUTO_ZOOM_MIN_SCALE_DIFF &&
    (stepType ? AUTO_ZOOM_INTERACTION_TYPES.has(stepType) : false);

  return {
    scale,
    focusX: Number(focusX.toFixed(1)),
    focusY: Number(focusY.toFixed(1)),
    shouldPersist,
  };
}

/**
 * Extract step type from various possible field names
 */
export function getStepType(step: StepData): string | null {
  return step.step_type || step.type || step.action_type || step.event_type || null;
}

/**
 * Extract element data from step (handles different field names)
 */
export function getElementData(step: StepData) {
  return step.element || step.element_data || null;
}

/**
 * Extract playback configuration from step
 */
export function getPlaybackConfig(step: StepData) {
  return step.annotations?.playback || null;
}

/**
 * Get bubble configuration from step
 */
export function getBubbleConfig(step: StepData): BubbleConfig | null {
  return step.annotations?.bubble || null;
}

/**
 * Get zoom configuration from step (saved or defaults)
 */
export function getZoomConfig(step: StepData) {
  const playbackConfig = getPlaybackConfig(step);
  
  if (playbackConfig?.zoom?.enabled) {
    return {
      ...playbackConfig.zoom,
      isCustom: true,
    };
  }

  const autoZoom = calculateAutoZoom(step);

  return {
    ...autoZoom,
    enabled: false,
    isCustom: false,
  };
}

/**
 * Generate a descriptive title for a step
 */
export function generateStepTitle(step: StepData, index: number): string {
  // Use annotation text if available
  if (step.annotations?.text) {
    return step.annotations.text;
  }

  const elementData = getElementData(step);
  const type = getStepType(step);

  if (!type) {
    return `Step ${index + 1}`;
  }

  // Get element identifier
  const elementName = getElementIdentifier(elementData);

  // Build human-readable description
  switch (type) {
    case "click":
      return `Click ${elementName}`;
      
    case "input":
    case "change":
      const value = step.value || elementData?.value;
      if (value) {
        const displayValue = value.length > 25 ? `${value.substring(0, 25)}...` : value;
        return `Type "${displayValue}"`;
      }
      return `Enter text in ${elementName}`;
      
    case "submit":
      return "Submit form";
      
    case "navigation":
      const url = elementData?.url || step.url;
      if (url) {
        try {
          const urlObj = new URL(url);
          const path = urlObj.pathname === "/" ? urlObj.hostname : urlObj.pathname;
          return `Go to ${path}`;
        } catch {
          return "Navigate to page";
        }
      }
      return "Navigate to page";
      
    case "scroll":
      return "Scroll page";
      
    default:
      return `${type.charAt(0).toUpperCase() + type.slice(1)} ${elementName}`;
  }
}

/**
 * Get element identifier for display
 */
function getElementIdentifier(elementData: any): string {
  if (!elementData) return "element";

  if (elementData.textContent) {
    const text = elementData.textContent.trim();
    return text.length > 30 ? `"${text.substring(0, 30)}..."` : `"${text}"`;
  }
  
  if (elementData.placeholder) {
    return `"${elementData.placeholder}"`;
  }
  
  if (elementData.id) {
    return `#${elementData.id}`;
  }
  
  if (elementData.tagName) {
    return `<${elementData.tagName.toLowerCase()}>`;
  }

  return "element";
}

/**
 * Generate action description for display
 */
export function generateActionDescription(step: StepData): string {
  const elementData = getElementData(step);
  const type = getStepType(step);

  let action = "";
  let target = "";

  // Determine action verb
  switch (type) {
    case "click":
      action = "Click";
      break;
    case "input":
    case "change":
      action = "Type in";
      break;
    case "submit":
      action = "Submit";
      break;
    case "navigation":
      action = "Navigate to";
      break;
    case "scroll":
      action = "Scroll";
      break;
    default:
      action = type ? type.charAt(0).toUpperCase() + type.slice(1) : "Interact with";
  }

  // Determine target
  if (elementData?.textContent) {
    const text = elementData.textContent.trim();
    target = text.length > 40 ? `"${text.substring(0, 40)}..."` : `"${text}"`;
  } else if (elementData?.placeholder) {
    target = `"${elementData.placeholder}" field`;
  } else if (elementData?.tagName) {
    target = `the ${elementData.tagName.toLowerCase()}`;
  } else {
    target = "element";
  }

  return `${action} ${target}`;
}
