import { useState, useEffect, useCallback, useRef } from 'react';
import type { StepData, BubbleConfig } from '../utils/step-helpers';

interface UseBubbleEditingProps {
  steps: StepData[];
  currentStepIndex: number;
  demoId: string;
  onBubbleChange?: () => void;
}

export function useBubbleEditing({
  steps,
  currentStepIndex,
  demoId,
  onBubbleChange,
}: UseBubbleEditingProps) {
  const [editingBubble, setEditingBubble] = useState<{ [key: number]: BubbleConfig }>({});
  const [isSaving, setIsSaving] = useState(false);
  const [modifiedSteps, setModifiedSteps] = useState<Set<number>>(new Set());
  const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  // Initialize bubble state from step annotations
  useEffect(() => {
    const currentStep = steps[currentStepIndex];
    if (currentStep && !editingBubble[currentStepIndex]) {
      const bubbleConfig = currentStep.annotations?.bubble;
      if (bubbleConfig) {
        setEditingBubble((prev) => ({
          ...prev,
          [currentStepIndex]: bubbleConfig,
        }));
      }
    }
  }, [currentStepIndex, steps]);

  const handleBubbleChange = useCallback(
    (
      stepIndex: number,
      field: 'text' | 'position',
      value: string
    ) => {
      setEditingBubble((prev) => ({
        ...prev,
        [stepIndex]: {
          ...prev[stepIndex],
          [field]: value,
          autoGenerated: false, // Mark as manually edited
        } as BubbleConfig,
      }));

      // Mark as modified
      setModifiedSteps((prev) => new Set(prev).add(stepIndex));

      // Notify parent for immediate preview
      if (onBubbleChange) {
        onBubbleChange();
      }

      // Debounced auto-save
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current);
      }

      saveTimeoutRef.current = setTimeout(async () => {
        const currentBubbleConfig = editingBubble[stepIndex];
        if (!currentBubbleConfig?.text) {
          // Don't save empty bubbles
          return;
        }

        const step = steps[stepIndex];
        if (!step?.id) return;

        setIsSaving(true);
        try {
          const config: BubbleConfig = {
            text: currentBubbleConfig.text,
            position: currentBubbleConfig.position || 'auto',
            autoGenerated: false,
          };

          const response = await fetch(
            `/api/demos/${demoId}/steps/${step.id}/bubble`,
            {
              method: 'PUT',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(config),
            }
          );

          if (response.ok) {
            // Optimistically update the local step's annotations
            if (!step.annotations) {
              step.annotations = {};
            }
            step.annotations.bubble = config;

            // Notify parent component
            if (onBubbleChange) {
              onBubbleChange();
            }
          }

          // Clear modified flag after save attempt
          setModifiedSteps((prev) => {
            const newSet = new Set(prev);
            newSet.delete(stepIndex);
            return newSet;
          });
        } catch (error) {
          // Silently handle errors
        } finally {
          setIsSaving(false);
        }
      }, 1000); // 1 second debounce
    },
    [demoId, steps, editingBubble, onBubbleChange]
  );

  const handleRemoveBubble = useCallback(
    async (stepIndex: number) => {
      const step = steps[stepIndex];
      if (!step?.id) return;

      setIsSaving(true);
      try {
        await fetch(`/api/demos/${demoId}/steps/${step.id}/bubble`, {
          method: 'DELETE',
        });

        // Remove from local state
        setEditingBubble((prev) => {
          const newState = { ...prev };
          delete newState[stepIndex];
          return newState;
        });

        // Clear from step annotations
        if (step.annotations) {
          delete step.annotations.bubble;
        }

        if (onBubbleChange) {
          onBubbleChange();
        }
      } catch (error) {
        // Silently handle errors
      } finally {
        setIsSaving(false);
      }
    },
    [demoId, steps, onBubbleChange]
  );

  return {
    editingBubble,
    isSaving,
    modifiedSteps,
    handleBubbleChange,
    handleRemoveBubble,
  };
}
